version: '3'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_letswatch
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
    volumes:
      - mysql_data:/var/lib/mysql/

  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver"
    volumes:
      - .:/app/
    ports:
      - "8000:8000"
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: localhost
      PMA_USER: root
      PMA_PASSWORD:
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  mysql_data: