version: "3.8"

networks:
  traefik:
    external: true
  letswatch:

services:
  backend:
    container_name: letswatch-backend
    image: letswatch-backend
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - config/env/.env
    networks:
      - letswatch
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.letswatch-backend.rule=Host(`api.letswatch.ir`)"
      - "traefik.http.routers.letswatch-backend.entrypoints=websecure"
      - "traefik.http.services.letswatch-backend.loadbalancer.server.port=8000"
      - "traefik.http.routers.letswatch-backend.tls=true"
      - "traefik.http.routers.letswatch-backend.tls.certresolver=production"