version: "3.8"

networks:
  tracer:
    external: true
    
services:
  backend:
    container_name: tracer-backend
    image: tracer-backend
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - config/env/.env
    networks:
      - tracer
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`api.tracer.finbright.org`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.services.backend.loadbalancer.server.port=8000"
      - "traefik.http.routers.backend.tls=true"
      - "traefik.http.routers.backend.tls.certresolver=production"
