# Generated by Django 4.2 on 2023-06-06 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_and_tag', '0002_video_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='cover',
            field=models.FileField(null=True, upload_to='vid_covers'),
        ),
    ]
