name: CI/CD Pipeline
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image
      run: |
        docker-compose build
    - name: Test
      run: |
        docker-compose run web python manage.py test
    - name: Migrate database
      run: |
        docker-compose run web python manage.py migrate

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up SSH keys for deployment
      uses: webfactory/ssh-agent@v0.5.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Deploy
      run: |
        ssh -o StrictHostKeyChecking=no -i $GITHUB_WORKSPACE/SE-KEY.pem ubuntu@188.121.118.178 "cd /home/backend/Back-end && sudo docker-compose pull && sudo docker-compose up -d"
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
