name: CI/CD Pipeline
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Install requirements
      run: |
        pip install -r requirements.txt
    - name: Make migrations
      run: |
        cd src
        python manage.py makemigrations
        python manage.py migrate
    - name: Run test
      run: |
        cd src
        python manage.py test
      
  CD:
    needs: CI
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deployment
        uses: docker://webfactory/ssh-agent:v0.5.0
        with:
          entrypoint: /bin/sh
          args: -c 'docker compose up -d --build'